# The URL the site will be built for
base_url = "https://nyanpasu64.gitlab.io"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

theme = "tale-zola"
title = "nyanpasu64's blog"
description = "Adventures in programming, DSP, and chiptune"

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

[extra]
# Put all your custom variables here
author = "nyanpasu64"

[extra.footer]
info = "Adventures in programming, DSP, and chiptune"
