name: Zola on GitHub Pages

on:
 push:
  branches:
   - master
   - '*'

jobs:
  build:
    name: Publish site
    runs-on: ubuntu-latest
    steps:
    - name: Checkout branch
      uses: actions/checkout@v3.0.0
      with:
        submodules: recursive
    - name: Build and deploy
      uses: ./.github/actions/zola-deploy-action
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
